#!/usr/bin/env python3
"""Regenerate docs/PROVIDER-DIVERGENCE-REPORT.md (issue B3 / T-028).

Runs the reference matchup under every credentialed declared provider in
fixtures/providers.yaml and publishes the measured divergence — trace-level
and outcome-level — rather than hiding it. Deterministic and offline: the
provider table is fixture data, no provider is ever called.

Usage: python3 tools/provider_divergence.py [--seeds N]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "core"))

import yaml  # noqa: E402

from core.arena import load_adl  # noqa: E402
from core.providers import declared_order, divergence_report, select_provider  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, default=50)
    args = ap.parse_args()

    bot_a = load_adl(ROOT / "adl" / "antweight-vault-defender.adl.yaml")
    bot_b = load_adl(ROOT / "adl" / "antweight-vault-raider.adl.yaml")
    avail = yaml.safe_load(open(ROOT / "fixtures" / "providers.yaml"))["providers"]

    rep = divergence_report(bot_a, bot_b, avail, range(args.seeds))
    sel = select_provider(bot_a, avail)

    lines = [
        "# Provider divergence report (generated)",
        "",
        "Generated by `python3 tools/provider_divergence.py` — do not hand-edit.",
        "Measures cross-provider behavioural divergence for the reference",
        "matchup on the deterministic engine (T-028). The provider table is",
        "**simulated fixture data** (`fixtures/providers.yaml`); no live",
        "provider is called — live cross-provider execution is a separate,",
        "approval-gated lane.",
        "",
        f"- Declared order (defender): `{declared_order(bot_a)}`",
        f"- Selection against the fixture table: `{sel['provider']}` "
        f"(status **{sel['status']}**, missing: {sel['missing'] or 'none'})",
        f"- Providers compared: `{rep['providersCompared']}`",
        f"- Seeds run: {len(rep['seedsRun'])}",
        f"- Trace divergence rate: **{rep['traceDivergenceRate']:.2f}** "
        "(any byte of the replayable evidence differs — the effective fuel "
        "scale is part of the trace)",
        f"- Outcome divergence rate: **{rep['outcomeDivergenceRate']:.2f}** "
        "(the winner changes between providers)",
        "",
        "## Divergence channel",
        "",
        f"{rep['channel']}.",
        "",
        "## Outcome-divergent seeds",
        "",
    ]
    if rep["outcomeDivergentSeeds"]:
        for s in rep["outcomeDivergentSeeds"]:
            lines.append(f"- seed {s}: winners {rep['divergentSeeds'][s]['winners']}")
    else:
        lines.append("None at the current reference configuration: matches "
                     "resolve before the fuel channel can flip an outcome. "
                     "The tie-break path (turn-limit matches decided on "
                     "absolute fuel) is where provider caps flip winners; "
                     "the suite exercises it directly (T-028).")
    lines.append("")

    out = ROOT / "docs" / "PROVIDER-DIVERGENCE-REPORT.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} — trace {rep['traceDivergenceRate']:.2f}, "
          f"outcome {rep['outcomeDivergenceRate']:.2f} over {len(rep['seedsRun'])} seeds")


if __name__ == "__main__":
    main()
